// store/useEditorStore.js

// 🧠 English:
// Editor state management for the visual canvas. Handles elements, selection, and editor modes.

// 💬 Español humano:
// Manejo del estado del editor visual. Controla elementos, selección y modos del editor.

import { create } from 'zustand';
import { v4 as uuidv4 } from 'uuid';

export const useEditorStore = create((set, get) => ({
  // State
  elements: [],
  selectedElementId: null,
  viewMode: 'both', // 'canvas', 'code', 'both'
  currentProject: null,
  userLevel: 'beginner',
  isDragging: false,
  canvasSize: { width: '100%', height: '600px' },
  
  // Actions
  addElement: (elementType, position = { x: 50, y: 50 }) => {
    try {
      console.debug(`🎯 [Store] addElement called for type: ${elementType}`, { elementType, position });
      
      const defaultProps = getDefaultProperties(elementType);
      console.debug(`🎯 [Store] Default properties for ${elementType}:`, defaultProps);
      
      const newElement = {
        id: uuidv4(),
        type: elementType,
        position,
        properties: defaultProps,
        timestamp: new Date().toISOString()
      };
      
      console.debug(`🎯 [Store] Created element for ${elementType}:`, newElement);
      console.debug(`🧩 Added ${elementType} element to canvas`, newElement);
      
      set(state => {
        const newState = {
          elements: [...state.elements, newElement],
          selectedElementId: newElement.id
        };
        console.debug(`🎯 [Store] State updated, total elements: ${newState.elements.length}`);
        return newState;
      });
      
      console.debug(`🎯 [Store] Successfully added ${elementType} element with ID: ${newElement.id}`);
      return newElement;
      
    } catch (error) {
      console.error(`❌ [Store] Error adding ${elementType} element:`, error);
      throw error;
    }
  },

  updateElement: (elementId, updates) => {
    console.debug(`🔧 Updated element ${elementId}`, updates);
    
    set(state => ({
      elements: state.elements.map(el => 
        el.id === elementId ? { ...el, ...updates } : el
      )
    }));
  },

  deleteElement: (elementId) => {
    console.debug(`🗑️ Deleted element ${elementId}`);
    
    set(state => ({
      elements: state.elements.filter(el => el.id !== elementId),
      selectedElementId: state.selectedElementId === elementId ? null : state.selectedElementId
    }));
  },

  selectElement: (elementId) => {
    console.debug(`👆 Selected element ${elementId}`);
    set({ selectedElementId: elementId });
  },

  clearSelection: () => {
    set({ selectedElementId: null });
  },

  setViewMode: (mode) => {
    console.debug(`👁️ View mode changed to: ${mode}`);
    set({ viewMode: mode });
  },

  setCurrentProject: (project) => {
    console.debug(`📁 Current project set:`, project?.name || 'New Project');
    set({ 
      currentProject: project,
      elements: project?.elements || []
    });
  },

  setUserLevel: (level) => {
    console.debug(`👤 User level set to: ${level}`);
    set({ userLevel: level });
  },

  clearCanvas: () => {
    console.debug('🧹 Canvas cleared');
    set({ 
      elements: [],
      selectedElementId: null
    });
  },

  setDragging: (isDragging) => {
    set({ isDragging });
  },

  // Getters
  getSelectedElement: () => {
    const { elements, selectedElementId } = get();
    return elements.find(el => el.id === selectedElementId) || null;
  },

  generateHTML: () => {
    const { elements } = get();
    return generateHTMLFromElements(elements);
  },

  generateCSS: () => {
    const { elements } = get();
    return generateCSSFromElements(elements);
  }
}));

// Helper functions
function getDefaultProperties(elementType) {
  const defaults = {
    text: {
      content: 'Sample Text',
      fontSize: '16px',
      color: '#000000',
      fontFamily: 'Arial, sans-serif',
      fontWeight: 'normal'
    },
    button: {
      content: 'Click Me',
      backgroundColor: '#007bff',
      color: '#ffffff',
      padding: '10px 20px',
      border: 'none',
      borderRadius: '4px',
      fontSize: '14px'
    },
    image: {
      src: 'https://via.placeholder.com/200x150',
      alt: 'Sample Image',
      width: '200px',
      height: '150px'
    }
  };
  
  return defaults[elementType] || {};
}

function generateHTMLFromElements(elements) {
  let html = '<!DOCTYPE html>\n<html lang="en">\n<head>\n';
  html += '    <meta charset="UTF-8">\n';
  html += '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '    <title>Skillwave Studio Project</title>\n';
  html += '    <link rel="stylesheet" href="styles.css">\n';
  html += '</head>\n<body>\n';
  
  elements.forEach(element => {
    html += generateElementHTML(element);
  });
  
  html += '</body>\n</html>';
  return html;
}

function generateCSSFromElements(elements) {
  let css = '/* Generated by Skillwave Studio */\n\n';
  css += 'body {\n    margin: 0;\n    padding: 20px;\n    font-family: Arial, sans-serif;\n}\n\n';
  
  elements.forEach(element => {
    css += generateElementCSS(element);
  });
  
  return css;
}

function generateElementHTML(element) {
  const { id, type, properties, position } = element;
  let html = '';
  
  switch (type) {
    case 'text':
      html = `    <div class="element-${id}" style="position: absolute; left: ${position.x}px; top: ${position.y}px;">${properties.content}</div>\n`;
      break;
    case 'button':
      html = `    <button class="element-${id}" style="position: absolute; left: ${position.x}px; top: ${position.y}px;">${properties.content}</button>\n`;
      break;
    case 'image':
      html = `    <img class="element-${id}" src="${properties.src}" alt="${properties.alt}" style="position: absolute; left: ${position.x}px; top: ${position.y}px;" />\n`;
      break;
    default:
      html = `    <div class="element-${id}" style="position: absolute; left: ${position.x}px; top: ${position.y}px;">Unknown Element</div>\n`;
  }
  
  return html;
}

function generateElementCSS(element) {
  const { id, type, properties } = element;
  let css = `.element-${id} {\n`;
  
  Object.entries(properties).forEach(([key, value]) => {
    if (key !== 'content' && key !== 'src' && key !== 'alt') {
      const cssProperty = key.replace(/([A-Z])/g, '-$1').toLowerCase();
      css += `    ${cssProperty}: ${value};\n`;
    }
  });
  
  css += '}\n\n';
  return css;
}